name: Scrape Jobs

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    branches:
      - main  # This triggers the workflow on new commits to the main branch

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Specify the version of Python you need

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Run script
      run: |
        source .venv/bin/activate
        python parse_multiple_listings.py
      env:
        TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        JOB_REPO_URL: ${{ secrets.JOB_REPO_URL }}
        LISTINGS_WEBHOOK_URL: ${{ secrets.LISTINGS_WEBHOOK_URL }}
        LOGS_WEBHOOK_URL: ${{ secrets.LOGS_WEBHOOK_URL }}
        REPO_NAME: ${{ secrets.REPO_NAME }}
        SECONDARY_REPO_URL: ${{ secrets.SECONDARY_REPO_URL }}

    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: script-logs
        path: logs.txt
